boa: support running Python code in non-blocking way
alibaba/pipcook pull request #602
Opened 2020-09-30 06:49 UTC by yorkie

It uses the Node.js worker_threads to start new thread to run Python functions.
Note that, we share the same Python interrupter.

2020-09-30 16:36 UTC, yorkie commented
@FeelyChau Just mark this PR be ready for review :)

2020-09-30 18:05 UTC, yorkie commented
Occurred the following error if running `npm test`:

```
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x000000010554b27e libpython3.7m.dylib`PyErr_FormatV + 30
    frame #1: 0x000000010554b239 libpython3.7m.dylib`PyErr_Format + 137
    frame #2: 0x0000000105478590 libpython3.7m.dylib`_PyObject_GenericGetAttrWithDict + 848
    frame #3: 0x0000000105477b26 libpython3.7m.dylib`PyObject_GetAttrString + 134
    frame #4: 0x0000000105477c4c libpython3.7m.dylib`PyObject_HasAttrString + 12
    frame #5: 0x000000010526c589 boa.node`boa::PythonObject::HasAttr(Napi::CallbackInfo const&) [inlined] pybind11::hasattr(obj=<unavailable>, name=<unavailable>) at pytypes.h:397:12 [opt]
    frame #6: 0x000000010526c584 boa.node`boa::PythonObject::HasAttr(this=0x00000001053091e0, info=0x00007ffeefbfc4a0) at object.cc:315 [opt]
    frame #7: 0x0000000105271a9b boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(this=<unavailable>)::'lambda'()::operator()() const at napi-inl.h:3838:12 [opt]
    frame #8: 0x00000001052719ca boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [inlined] napi_value__* Napi::details::WrapCallback<Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::'lambda'()>(Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::'lambda'()) at napi-inl.h:73:12 [opt]
    frame #9: 0x00000001052719c5 boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(env=0x000000010500b280, info=0x00007ffeefbfc580) at napi-inl.h:3831 [opt]
    frame #10: 0x000000010006346a node`v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke(v8::FunctionCallbackInfo<v8::Value> const&) + 122
    frame #11: 0x00000001002580c8 node`v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 616
    frame #12: 0x000000010025765c node`v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 524
    frame #13: 0x0000000100256d82 node`v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 258
    frame #14: 0x0000000100a50f59 node`Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
```

2020-09-30 19:16 UTC, yorkie commented
> Occurred the following error if running `npm test`:
> 
> ```
> * thread #1, stop reason = signal SIGSTOP
>   * frame #0: 0x000000010554b27e libpython3.7m.dylib`PyErr_FormatV + 30
>     frame #1: 0x000000010554b239 libpython3.7m.dylib`PyErr_Format + 137
>     frame #2: 0x0000000105478590 libpython3.7m.dylib`_PyObject_GenericGetAttrWithDict + 848
>     frame #3: 0x0000000105477b26 libpython3.7m.dylib`PyObject_GetAttrString + 134
>     frame #4: 0x0000000105477c4c libpython3.7m.dylib`PyObject_HasAttrString + 12
>     frame #5: 0x000000010526c589 boa.node`boa::PythonObject::HasAttr(Napi::CallbackInfo const&) [inlined] pybind11::hasattr(obj=<unavailable>, name=<unavailable>) at pytypes.h:397:12 [opt]
>     frame #6: 0x000000010526c584 boa.node`boa::PythonObject::HasAttr(this=0x00000001053091e0, info=0x00007ffeefbfc4a0) at object.cc:315 [opt]
>     frame #7: 0x0000000105271a9b boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(this=<unavailable>)::'lambda'()::operator()() const at napi-inl.h:3838:12 [opt]
>     frame #8: 0x00000001052719ca boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [inlined] napi_value__* Napi::details::WrapCallback<Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::'lambda'()>(Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::'lambda'()) at napi-inl.h:73:12 [opt]
>     frame #9: 0x00000001052719c5 boa.node`Napi::ObjectWrap<boa::PythonObject>::InstanceMethodCallbackWrapper(env=0x000000010500b280, info=0x00007ffeefbfc580) at napi-inl.h:3831 [opt]
>     frame #10: 0x000000010006346a node`v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke(v8::FunctionCallbackInfo<v8::Value> const&) + 122
>     frame #11: 0x00000001002580c8 node`v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 616
>     frame #12: 0x000000010025765c node`v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 524
>     frame #13: 0x0000000100256d82 node`v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 258
>     frame #14: 0x0000000100a50f59 node`Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
> ```

This is addressed, the sub-thread would call to the `finalize_interpreter()` which causes the following calls to Python would crash, just added an extra state `initialized` to flag the finalization op must be in the main thread and `Py_IsInitialized()` is true.

2020-10-01 13:39 UTC, yorkie commented
@FeelyChau See https://github.com/alibaba/pipcook/pull/602/checks?check_run_id=1192579536, it seems failed by daemon tests.

2020-10-02 09:32 UTC, FeelyChau commented
> @FeelyChau See https://github.com/alibaba/pipcook/pull/602/checks?check_run_id=1192579536, it seems failed by daemon tests which are not related to this PR.

OK, I'll check it out.

2020-10-10 02:15 UTC, WenheLI approved these changes
LGTM

2020-10-10 09:52 UTC, FeelyChau requested changes

2020-10-10 09:52 UTC, FeelyChau commented on packages/boa/src/core/object.h
> +  bool _owned;
We can use `std::atomic_flag` instead to improve performance.

2020-10-10 15:04 UTC, FeelyChau commented
LGTM.

2020-10-10 15:04 UTC, FeelyChau approved these changes

2020-10-10 15:06 UTC, merged