Bench: Add config for circleCI
alibaba/pipcook pull request #606
Opened 2020-10-09 09:09 UTC by WenheLI

This PR adds supports for circleci benchmarking scripts

2020-10-09 16:20 UTC, yorkie requested changes
Shall we run the task when PR updates?

2020-10-09 16:21 UTC, yorkie commented
And I think we can't run it on the current main branch: https://app.circleci.com/pipelines/github/alibaba/pipcook

2020-10-10 02:00 UTC, WenheLI commented
> https://app.circleci.com/pipelines/github/alibaba/pipcook

Set it only to run CI when PR is submitted.

2020-10-26 05:54 UTC, yorkie commented on tools/benchmark.sh
> +git config user.name "WenheLI"
Could the above lines be configurable?

2020-10-26 05:58 UTC, yorkie commented on tools/benchmark.sh
> +git push -q https://${TOKEN}@github.com/imgcook/pipcook-benchmark.git
I don't expect the result will be pushed to the benchmark repo if I run this locally, how about `sh tools/benchmark.sh --token=xxx`?

2020-10-26 05:59 UTC, yorkie commented on .circleci/config.yml
> +  bench:
```suggestion
  benchmark:
```

2020-10-26 06:00 UTC, yorkie commented
We need documentation about this change.

2020-10-27 03:44 UTC, WenheLI commented on tools/benchmark.sh
> +git config user.name "WenheLI"
Make it configurable via CircleCI

2020-10-27 05:00 UTC, yorkie commented on tools/benchmark.sh
> +  echo "benchmark has been saved to data.json!"
How about print the output only when not uploading?

2020-10-27 05:01 UTC, yorkie commented on tools/benchmark.sh
> +fi
EOF

2020-10-27 08:35 UTC, yorkie requested changes

2020-10-27 08:35 UTC, yorkie commented on tools/benchmark.sh
> +  echo "{\"install_time\":${install_time}, \"init_time\":$init_time, \"esbuild_time\":$esbuild_time, \"build_time\":$build_time, \"test_time\":$test_time, \"mnist_time\":$mnist_time, \"timestamp\": $
This line is too long.

2020-10-27 08:35 UTC, yorkie commented on tools/benchmark.sh
> +            '. + [{install_time:$install_time, init_time:$init_time, esbuild_time:$esbuild_time, build_time:$build_time, test_time:$test_time, mnist_time:$mnist_time, timestamp: $time_stamp }]')  > d
Ditto.

2020-10-27 08:35 UTC, yorkie commented on tools/benchmark.sh
> +  git commit --allow-empty  -am\"[circleci]: update data"
```suggestion
  git commit --allow-empty -am\"update data"
```

2020-10-27 08:36 UTC, yorkie commented on .circleci/config.yml
> +      - bench
```suggestion
      - benchmark
```

2020-10-27 08:36 UTC, yorkie commented
@WenheLI What are the hooks to run this script in CircleCI?

2020-10-28 08:09 UTC, WenheLI commented
> @WenheLI What are the hooks to run this script in CircleCI?

This will run after every `PR` is merged.

2020-10-28 08:12 UTC, yorkie commented
> > @WenheLI What are the hooks to run this script in CircleCI?
> 
> This will run after every `PR` is merged.

It seems incorrect, we should run when PR updates.

2020-10-28 12:13 UTC, WenheLI commented
> > > @WenheLI What are the hooks to run this script in CircleCI?
> > 
> > 
> > This will run after every `PR` is merged.
> 
> It seems incorrect, we should run when PR updates.

Humm, that's true. I will update it later

2020-10-29 03:31 UTC, WenheLI commented
@yorkie Just came into my mind, since we want to keep recording the benchmark data, we should only run this benchmark when pr is merged. We can run another job for benchmarking on every commit.

2020-10-29 06:45 UTC, yorkie commented
Ok, then we should also declare the hooks explicitly that we used.

2020-10-29 07:53 UTC, WenheLI commented
> Ok, then we should also declare the hooks explicitly that we used.

Limit the CI only upload benchmark results when committing to master. In other cases, it will only print out the result.

2020-10-29 08:15 UTC, yorkie commented
> > Ok, then we should also declare the hooks explicitly that we used.
> 
> Limit the CI only upload benchmark results when committing to master. In other cases, it will only print out the result.

See https://circleci.com/docs/2.0/configuration-cookbook/#branch-filtering-for-job-steps, we need to config it in circle config.

2020-10-29 09:41 UTC, yorkie approved these changes

2020-10-29 09:43 UTC, merged