doc: add colab link to install doc and readme
alibaba/pipcook pull request #612
Opened 2020-10-13 02:48 UTC by FeelyChau

Add colab link to `INSTALL.md` and `README.md`.

2020-10-13 05:12 UTC, yorkie requested changes

2020-10-13 05:12 UTC, yorkie commented on README.md
> +You also can try [Pipcook][] online with [Google Colab Notebook](https://colab.research.google.com/github/alibaba/pipcook/blob/master/notebooks/pipcook_image_classification.ipynb).
The colab should not be in the Pipboard section.

2020-10-13 05:12 UTC, yorkie commented on docs/INSTALL.md
> +- [Google Colab Notebook](https://colab.research.google.com/github/alibaba/pipcook/blob/master/notebooks/pipcook_image_classification.ipynb) **Google Colab** is a free GPU / TPU training platform pro
Ditto, this is not for installing Pipcook on Colab.

2020-11-09 02:31 UTC, FeelyChau commented
We need to create some notebooks to let Pipcook run on Colab.

2020-11-09 08:59 UTC, yorkie commented
> We need to create some notebooks to let Pipcook run on Colab.

We have written some at https://github.com/alibaba/pipcook/tree/master/notebooks.

2020-12-01 08:22 UTC, yorkie approved these changes

2020-12-01 08:22 UTC, merged