.CONDA_INSTALL_DIR 修改成可以支持相对目录
alibaba/pipcook pull request #655
Opened 2020-12-05 06:57 UTC by hongyin163

项目里构建环境和线上环境的目录结构不一样，构建好后发到线上，.CONDA_INSTALL_DIR 里的目录就不对了。

看了源代码，所以想设置环境变量 BOA_CONDA_PREFIX 来解决，设置了相对路径，但是执行 npm run build 的时候提示找不到python.3 ……，应该是 binding.gyp 配置文件中取的是路径不对，这里配置修了一下，还有 util 里的 getCondaPath 函数，改成相对包的根目录查找。

本地测试没问题，请帮忙 review，更新 npm 包，多谢！！

2020-12-05 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/pipcook?pullRequest=655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/pipcook?pullRequest=655) before we can accept your contribution.<br/><hr/>**lihongyin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/pipcook?pullRequest=655) it.</sub>

2020-12-05 07:56 UTC, yorkie requested changes

2020-12-05 07:56 UTC, yorkie commented on packages/boa/tools/utils.js
> +}
```suggestion
};
```

2020-12-05 07:57 UTC, yorkie commented
多谢贡献！另外，需要按照上面的提示签一下我们的 CLA 哦。

2020-12-05 08:45 UTC, yorkie commented
@hongyin163 还需要统一下你每个 commit 的作者（邮箱），以及确保邮箱是注册过 CLA 的哈～

2020-12-05 08:46 UTC, yorkie commented
@hongyin163 另外可以稍微贴一下，之前遇到问题时的构建环境和线上环境吗？

2020-12-05 08:48 UTC, hongyin163 commented
> @hongyin163 还需要统一下你每个 commit 的作者（邮箱），以及确保邮箱是注册过 CLA 的哈～

好的

2020-12-05 09:39 UTC, hongyin163 commented
> @hongyin163 另外可以稍微贴一下，之前遇到问题时的构建环境和线上环境吗？
完善了，构建环境和线上基本一样，就是部署的目录不一样，线上提示下面的异常：

`error while loading shared libraries: libpython3.7m.so.1.0`

2020-12-05 09:44 UTC, yorkie approved these changes

2020-12-05 09:47 UTC, yorkie commented
@hongyin163 LGTM, 另外能请你把提交 squash 一下，并使用英文写 commit message 吗？因为项目里面还是需要使用英文撰写提交记录。

2020-12-05 09:53 UTC, hongyin163 commented
> @hongyin163 LGTM, 另外能请你把提交 squash 一下，并使用英文写 commit message 吗？因为项目里面还是需要使用英文撰写提交记录。

好的，我完善一下

2020-12-05 11:02 UTC, hongyin163 commented
> @hongyin163 LGTM, 另外能请你把提交 squash 一下，并使用英文写 commit message 吗？因为项目里面还是需要使用英文撰写提交记录。

改好了，帮忙看下，多谢~

2020-12-05 14:24 UTC, yorkie commented
好像代码里有冲突，需要解决一下哦

2020-12-07 02:59 UTC, hongyin163 commented
> 好像代码里有冲突，需要解决一下哦

冲突已经解决

2020-12-07 04:26 UTC, yorkie commented
还有一个小问题，我们使用的 yarn 开发，所以 package-lock 文件需要删掉。

2020-12-07 05:06 UTC, hongyin163 commented
> 还有一个小问题，我们使用的 yarn 开发，所以 package-lock 文件需要删掉。

已经删除

2020-12-07 07:25 UTC, FeelyChau requested changes

2020-12-07 07:25 UTC, FeelyChau commented on packages/boa/tools/utils.js
> +
感谢PR！
最大空行数为 1 行，这里需要删除一行。

2020-12-07 08:49 UTC, hongyin163 commented on packages/boa/tools/utils.js
> +
感谢这个项目！

空行已删除

2020-12-07 10:30 UTC, hongyin163 commented
@yorkie 你好，单测里有个网络的异常，帮忙看看

2020-12-07 12:01 UTC, yorkie commented
> @yorkie 你好，单测里有个网络的异常，帮忙看看

已经重新开启 CI

2020-12-07 12:39 UTC, FeelyChau approved these changes
LGTM.

2020-12-07 12:42 UTC, merged

2020-12-07 12:43 UTC, FeelyChau commented
@hongyin163 PR 已合并，Pipcook 项目支持每日构建，你可以通过
```sh
$ pipcook init beta
```
来安装 beta 版本来运行最新版本的代码，每日构建版本会在每天凌晨发布。

2020-12-08 02:06 UTC, hongyin163 commented
> @hongyin163 PR 已合并，Pipcook 项目支持每日构建，你可以通过
> 
> ```shell
> $ pipcook init beta
> ```
> 
> 来安装 beta 版本的 Pipcook， 或者如果你只是使用了 boa, 那么修改 boa 的版本为 `beta`，并重新安装，就可以安装最新版本的代码，每日构建版本会在每天凌晨发布。

好的，多谢！

2020-12-09 10:16 UTC, hongyin163 commented
> @hongyin163 PR 已合并，Pipcook 项目支持每日构建，你可以通过
> 
> ```shell
> $ pipcook init beta
> ```
> 
> 来安装 beta 版本的 Pipcook， 或者如果你只是使用了 boa, 那么修改 boa 的版本为 `beta`，并重新安装，就可以安装最新版本的代码，每日构建版本会在每天凌晨发布。

你好，我本地安装beta版本，但是还是没有变更到新版本，当前版本是：1.2.1-1b50e4e-beta.0

2020-12-09 10:27 UTC, yorkie commented
```
Error: Unable to process command '::set-env name=UPDATED::true' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

@hongyin163 应该是 GitHub 因为安全原因导致我们 beta 包的 build 失败了。

2020-12-09 10:36 UTC, yorkie commented
@hongyin163 多谢反馈，我在 #663 中修复，今天会合并进去，看看明天是否生效。

2020-12-10 02:36 UTC, hongyin163 commented
> @hongyin163 多谢反馈，我在 #663 中修复，今天会合并进去，看看明天是否生效。

今天好像还是没生效？

2020-12-10 03:08 UTC, yorkie commented
@hongyin163 可以再试试，在 npm 上已经看到最新的版本 1.2.1-5caa176-beta.0，具体原因见 #664～