cli: add new command to use create-pipcook-plugin
alibaba/pipcook pull request #657
Opened 2020-12-08 12:14 UTC by yorkie

See https://github.com/imgcook/create-pipcook-plugin. This PR adds a new command to use create-pipcook-plugin to improve the UX for plugin developers:

```sh
$ pipcook plugin create foobar --category data-collect
```

This deprecated the old `dev-plugin` command which will be removed at 2.0 :)

2020-12-08 12:37 UTC, yorkie commented
@FeelyChau CI is green :)

2020-12-09 04:49 UTC, FeelyChau requested changes

2020-12-09 04:49 UTC, FeelyChau commented on docs/zh-cn/contributing/contribute-a-plugin.md
>  插件开发从一行命令开始：`pipcook plugin-dev`：
```suggestion
插件开发从一行命令开始：`pipcook plugin create`：
```

2020-12-09 05:53 UTC, rickycao-qy approved these changes
LGTM

2020-12-09 06:37 UTC, FeelyChau approved these changes
LGTM.

2020-12-10 09:01 UTC, WenheLI approved these changes
LGTM

2020-12-10 11:35 UTC, merged