boa: use $ORIGIN/@loader_path to set RPATH
alibaba/pipcook pull request #667
Opened 2020-12-11 05:47 UTC by yorkie

This uses a relative path as RPATH to address the rebuild issue when a package path is relocated. It also fixes the $ORIGIN usage on macOS, uses `@loader_path` on macOS, that `$ORIGIN` is working on Linux only.

2020-12-11 05:47 UTC, yorkie commented
See https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html for RPATH on macOS.

2020-12-11 06:10 UTC, hongyin163 commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
这里可能会有问题，默认了.miniconda目录在根目录，如果设置BOA_CONDA_PREFIX=test，miniconda就在test/.miniconda里了

2020-12-11 06:23 UTC, yorkie commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
之前加入 BOA_CONDA_PREFIX 是为了使用用户自己的 conda，所以有下面几种情况：

- PREFIX 是 `@package`，表示使用了默认 boa 的 conda
- PREFIX 是 `@cwd`，表示使用了以当前用户的目录
- PREFIX 是其他路径，比如 test，表示用户自己声明的目录

第一种情况下，与不声明的情况类似，可以保留现有的规则，第三种情况下，可以根据 PREFIX 和当前目录得到最终的 RPATH。

但是第二种，@hongyin163 你有没有什么好的建议呢？

2020-12-11 06:32 UTC, hongyin163 commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
我这里设置BOA_CONDA_PREFIX，是因为构建和线上目录不一致，所以在.CONDA_INSTALL_DIR文件里不能存绝对路径，这个路径计算最好是以.CONDA_INSTALL_DIR里存的路径来推算，以.CONDA_INSTALL_DIR为准

2020-12-11 07:00 UTC, yorkie commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
所以，你使用的都是通过 Boa 安装的 Conda 包吗？

2020-12-11 07:02 UTC, hongyin163 commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
是的

2020-12-11 07:15 UTC, hongyin163 commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
> 所以，你使用的都是通过 Boa 安装的 Conda 包吗？

我应该推动在线上环境预装 conda 吧，不然每次都安装也是费劲

2020-12-11 07:47 UTC, yorkie commented on packages/boa/binding.gyp
> +            "-Wl,-rpath,'@loader_path/../../<!@(node -p \"require('./tools/utils').getCondaName()\")/lib'"
好的，我知道了，我晚上再修改一个版本

2020-12-14 07:30 UTC, yorkie commented on packages/boa/tools/utils.js
> +    }
@hongyin163 这里的逻辑调整为 BOA_CONDA_PREFIX 是 `@package`（默认）时，会使用相对路径，其他情况都使用绝对路径。

你之前说的场景是在机器 A 安装好后，迁移到机器 B 的路径，按照我的理解，应该不需要声明 BOA_CONDA_PREFIX，因为 conda 的路径都是相对当前 boa 目录来检索的。

2020-12-14 07:39 UTC, hongyin163 commented on packages/boa/tools/utils.js
> +    }
对，这样可以

2020-12-14 11:44 UTC, FeelyChau requested changes

2020-12-14 11:44 UTC, FeelyChau commented on packages/boa/tools/utils.js
> +  checkPythonInstalledOn(prefix) {
The name of the function does not matche with current implement.

2020-12-14 13:23 UTC, yorkie commented
Updated @FeelyChau :)

2020-12-14 13:25 UTC, FeelyChau approved these changes
LGTM.

2020-12-15 03:21 UTC, hongyin163 commented
LGTM

2020-12-15 06:15 UTC, rickycao-qy approved these changes
LGTM

2020-12-15 08:28 UTC, merged