upgrade axios to 0.21.1
alibaba/pipcook pull request #687
Opened 2021-01-06 07:50 UTC by FeelyChau

For security reason, we need to upgrade axios to v0.21.1.

2021-01-11 04:31 UTC, yorkie requested changes

2021-01-11 04:31 UTC, yorkie commented on packages/cli/package.json
> +    "axios": ">=0.21.1",
```suggestion
    "axios": "^0.21.1",
```

2021-01-11 04:31 UTC, yorkie commented on packages/daemon/package.json
> +    "axios": ">=0.21.1",
Ditto

2021-01-11 04:31 UTC, yorkie commented on packages/sdk/package.json
> +    "axios": ">=0.21.1",
Ditto

2021-01-11 10:01 UTC, FeelyChau commented
Fixed,  @yorkie  may I ask you to review again?

2021-01-12 05:22 UTC, yorkie commented
You need to reinstall to update the yarn lock files.

2021-01-15 01:28 UTC, yorkie approved these changes

2021-01-15 06:54 UTC, WenheLI approved these changes
LGTM

2021-01-15 06:56 UTC, merged