deamone, wasm: add tvm for 2.0
alibaba/pipcook pull request #691
Opened 2021-01-14 14:06 UTC by WenheLI

2021-01-15 06:56 UTC, yorkie requested changes

2021-01-15 07:07 UTC, yorkie requested changes
Added more reviews.

2021-01-15 07:07 UTC, yorkie commented on packages/cli/src/bin/pipcook.ts
> +    .description("add essential libs and deps for pipcook");
```suggestion
    .description('add libraries: tvm, tensorflow, pytorch...');
```

2021-01-15 07:07 UTC, yorkie commented on packages/daemon/.eslintignore
> +templates/*
EOF

2021-01-15 07:07 UTC, yorkie commented on packages/daemon/src/convertor/keras.ts
> +    process.send('done');
Shall we have a binary or JSON-based spec instead of the plain text?

2021-01-15 07:07 UTC, yorkie commented on packages/daemon/src/generator/tvm.cli.ts
> +  console.error(`The convert type is ${inputModel} but only ${validModel.join(', ')} are available`);
Prints: process.exit(1);

2021-01-15 07:07 UTC, yorkie commented on packages/daemon/src/generator/tvm.ts
> +    client.on('error', (e) => reject(e));
```suggestion
    client.on('error', reject);
```

2021-01-15 07:07 UTC, yorkie commented on packages/daemon/src/generator/tvm.ts
> +    client.on('message', () => resolve({}));
Again, we need to handle the binary/JSON to ensure this is complete correctly :)

2021-01-15 07:07 UTC, yorkie commented on test/sdk/job.ts
> +    const metadata = await readJson(path.join(__dirname, 'output', 'nodejs', 'metadata.json'));
```suggestion
    const metadata = await readJson(path.join(__dirname, 'output/nodejs/metadata.json'));
```

2021-01-15 07:08 UTC, yorkie commented
@WenheLI this PR requires a Chinese tutorial and some tests to be merged.

2021-01-18 11:08 UTC, FeelyChau requested changes

2021-01-18 11:08 UTC, FeelyChau commented on packages/daemon/src/convertor/keras.ts
> +  relay = boa.import('tvm.relay');
I think we should export a function to initialize the tvm for testability.

2021-01-25 05:30 UTC, FeelyChau requested changes
This branch should rebase to main.

2021-01-25 05:39 UTC, FeelyChau requested changes

2021-01-25 05:39 UTC, FeelyChau commented on packages/daemon/src/generator/tvm.ts
> +        reject('Internal Error');
I think reject should always called with Error object.

2021-01-25 05:39 UTC, FeelyChau commented on packages/daemon/src/generator/tvm.ts
> +        resolve({});
```suggestion
        resolve();
```

2021-01-25 11:29 UTC, FeelyChau requested changes

2021-01-26 07:28 UTC, yorkie commented on packages/daemon/src/convertor/keras.ts
> +    fs.copy(path.join(__dirname, `../../templates/wasm/`), `${dist}/wasm/`),
```suggestion
    fs.copy(path.join(__dirname, '../../templates/wasm/'), `${dist}/wasm/`),
```

No need to use string template.

2021-01-26 07:29 UTC, yorkie commented on packages/daemon/src/convertor/keras.ts
> +    process.send(1);
@FeelyChau I remember that you pointed this could be implemented in the exit code?

2021-01-26 07:29 UTC, yorkie commented on packages/daemon/src/generator/nodejs.ts
> +    fs.copy(path.join(__dirname, `../../templates/node/predict.js`), `${dist}/nodejs/index.js`),
```suggestion
    fs.copy(path.join(__dirname, '../../templates/node/predict.js'), `${dist}/nodejs/index.js`),
```

2021-01-26 07:30 UTC, yorkie commented on packages/daemon/src/generator/tvm.ts
> +  return new Promise((resolve, reject) => {
```suggestion
  return new Promise<void>((resolve, reject) => {
```

2021-01-26 07:30 UTC, yorkie commented on packages/sdk/src/lib.ts
> +   */
Duplicated?

2021-01-26 07:31 UTC, yorkie commented on packages/daemon/templates/wasm/node.js
> +  console.log(output.toArray());
Could this log be removed?

2021-01-26 15:17 UTC, FeelyChau requested changes

2021-01-26 15:17 UTC, FeelyChau commented on packages/daemon/src/generator/tvm.cli.ts
> +      console.error(e);
Should the error be ignored?

2021-01-26 15:17 UTC, FeelyChau commented on packages/daemon/src/generator/tvm.ts
> +  console.log(files.filter((it) => it.endsWith('h5')).length);
Remove logs.

2021-01-26 15:17 UTC, FeelyChau commented on packages/daemon/src/controllers/lib.controller.ts
> +    return await this.libService.installByName(name);
Should return void with code 204.

2021-01-26 15:17 UTC, FeelyChau commented on packages/daemon/src/services/lib.service.ts
> +  async installByName(name: string): Promise<boolean> {
I think it's better to throw out the error.

2021-01-26 15:17 UTC, FeelyChau commented on packages/daemon/templates/wasm/browser.js
> +  const wasm = await wasmSource.arrayBuffer();
```js
const [ wasm, param, graph, modelSpec ] = await Promise.all([
  wasmSource.arrayBuffer(),
  params.arrayBuffer(),
  desc.json(),
  spec.json()
]);
```

2021-02-03 04:55 UTC, FeelyChau requested changes

2021-02-03 04:55 UTC, FeelyChau commented on packages/daemon/src/generator/tvm.ts
> +export async function generateTVM(dist: string, projPackage: any, opts: GenerateOptions): Promise<void> {
If `projPackage` is a object, it should be `Record<string, any>`.
And this function should be tested.

2021-02-05 08:08 UTC, yorkie approved these changes

2021-02-05 08:09 UTC, FeelyChau approved these changes
LGTM.

2021-02-05 12:55 UTC, rickycao-qy approved these changes
LGTM

2021-02-05 13:08 UTC, merged