cli: show download progress
alibaba/pipcook pull request #726
Opened 2021-03-19 18:54 UTC by FeelyChau

Show download progress when download framework and scripts.
Because the function `downloadAndExtractTo` with progress should not used by scripts (not all the runtime run in terminal), I copy and modify it in `cli`.

2021-03-23 02:29 UTC, yorkie requested changes

2021-03-23 02:29 UTC, yorkie commented on packages/cli/package.json
> +    "@types/cli-progress": "^3.9.1",
Type packages should be in devDependencies.

2021-03-23 13:20 UTC, rickycao-qy commented
CI is failed

2021-03-25 11:24 UTC, WenheLI approved these changes
LGTM

2021-03-25 17:41 UTC, yorkie approved these changes

2021-03-26 03:01 UTC, rickycao-qy approved these changes
LGTM

2021-03-26 03:03 UTC, WenheLI approved these changes

2021-03-26 03:04 UTC, merged