Feat/add resnet
alibaba/pipcook pull request #757
Opened 2021-04-09 07:53 UTC by WenheLI

2021-04-09 14:00 UTC, yorkie commented on example/pipelines/resnet.v2.json
> +    "framework": "tf2@1.0.0",
tf2's 1.0.0? It seems weird a bit :(

2021-04-09 14:16 UTC, FeelyChau requested changes

2021-04-09 14:16 UTC, FeelyChau commented on example/pipelines/resnet.v2.json
> +      "epochs": 1,
As an example, we should set a normal value.

2021-06-11 07:24 UTC, yorkie commented
Any updates? @WenheLI

2021-06-11 08:56 UTC, WenheLI commented
@yorkie - The only thing that needs to take care of is the naming of `framework`. `tf2@1.0.0` does sound weird. Any suggestions for the naming?

2021-06-11 09:42 UTC, yorkie commented
> @yorkie - The only thing that needs to take care of is the naming of `framework`. `tf2@1.0.0` does sound weird. Any suggestions for the naming?

tf@2.0.0?

2021-06-12 04:56 UTC, WenheLI commented
> > @yorkie - The only thing that needs to take care of is the naming of `framework`. `tf2@1.0.0` does sound weird. Any suggestions for the naming?
> 
> tf@2.0.0?

@FeelyChau - This might need cooperation.

2021-06-13 13:19 UTC, FeelyChau commented
@WenheLI @yorkie We can name it correctly if we can define the framework clearly. According to our current implementation, framework is a set of runtime dependencies of a pipeline, if we follow this definition, maybe `tf-resnet` will be a better name.

2021-06-15 09:40 UTC, WenheLI commented
> @WenheLI @yorkie We can name it correctly if we can define the framework clearly. According to our current implementation, framework is a set of runtime dependencies of a pipeline, if we follow this definition, maybe `tf-resnet` will be a better name.

IMO, the runtime that resnet depends on might have little to no differences with others. That means a specific runtime for `resnet` might be a bit weird

2021-08-05 12:39 UTC, FeelyChau commented
`resnet` has been implemented by #811 .

2021-08-05 12:39 UTC, closed without merging